COMMONTAIL_NO_IMAGE_PLACEHOLDER_TITLE: str = '__IMAGE_LATER__'
COMMONTAIL_OPENGRAPH_CACHE_LIFETIME = 86400
COMMONTAIL_PAGINATION_NEIGHBOURS_COUNT = 2
COMMONTAIL_STRUCTURED_DATA_CACHE_LIFETIME = 86400
COMMONTAIL_SITEMAP_DEFAULT_INCLUDE: bool = True
COMMONTAIL_SITEMAP_DEFAULT_ALLOW_INDEXING: bool = True
COMMONTAIL_SITEMAP_DEFAULTS: Tuple[str, float] = ('weekly', 0.5)
