from typing import Tuple

COMMONTAIL_CONTENT_STREAM_PAGE_BODY_BLOCK: str = 'commontail.blocks.ContentStreamBlock'

COMMONTAIL_NO_IMAGE_PLACEHOLDER_TITLE: str = '__IMAGE_LATER__'

COMMONTAIL_OPENGRAPH_CACHE_LIFETIME: int = 86400

COMMONTAIL_PAGINATION_NEIGHBOURS_COUNT: int = 2

COMMONTAIL_SITEMAP_DEFAULT_INCLUDE: bool = True
COMMONTAIL_SITEMAP_DEFAULT_ALLOW_INDEXING: bool = True
COMMONTAIL_SITEMAP_DEFAULTS: Tuple[str, float] = ('weekly', 0.5)

COMMONTAIL_STRUCTURED_DATA_CACHE_LIFETIME: int = 86400
