# Generated by Django 3.2.12 on 2022-03-28 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
        ('commontail', '0003_auto_20220324_1319'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageViewsCounter',
            fields=[
                ('page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='+', serialize=False, to='wagtailcore.page', verbose_name='page')),
                ('views_count', models.PositiveBigIntegerField(db_index=True, verbose_name='views count')),
            ],
            options={
                'verbose_name': 'счётчик посещений',
                'verbose_name_plural': 'счётчики посещений',
            },
        ),
    ]
