# Generated by Django 3.2.14 on 2022-07-27 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('commontail', '0005_auto_20220405_2013'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalPermission',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.permission',),
        ),
        migrations.AlterField(
            model_name='menu',
            name='handle',
            field=models.SlugField(help_text='Must be unique per site, will be used as a reference by rendering tag.', max_length=100, verbose_name='handle'),
        ),
        migrations.AlterField(
            model_name='namedreference',
            name='handle',
            field=models.SlugField(help_text='Must be unique per site, will be used as a reference by rendering tag.', max_length=100, verbose_name='handle'),
        ),
        migrations.AlterField(
            model_name='pageviewscounter',
            name='page',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='views_counter', serialize=False, to='wagtailcore.page', verbose_name='page'),
        ),
        migrations.AlterUniqueTogether(
            name='menu',
            unique_together={('site', 'handle')},
        ),
    ]
