# Generated by Django 3.2.15 on 2022-09-08 13:23

from django.db import migrations
import wagtail.blocks
import wagtail.documents.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('commontail', '0007_auto_20220907_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='items',
            field=wagtail.fields.StreamField([('category', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(label='Menu category title', max_length=64, required=True)), ('items', wagtail.blocks.StreamBlock([('document', wagtail.blocks.StructBlock([('document', wagtail.documents.blocks.DocumentChooserBlock(label='Document', required=True)), ('link_text', wagtail.blocks.CharBlock(label="Link's text", max_length=64, required=False))])), ('external', wagtail.blocks.StructBlock([('link_text', wagtail.blocks.CharBlock(label="Link's text", max_length=64, required=False)), ('url', wagtail.blocks.URLBlock(label='URL', required=True))])), ('page', wagtail.blocks.StructBlock([('link_text', wagtail.blocks.CharBlock(label="Link's text", max_length=64, required=False)), ('page', wagtail.blocks.PageChooserBlock(label='Page', required=True)), ('query_string', wagtail.blocks.CharBlock(label='Query string', max_length=255, required=False))])), ('subcategory', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(label='Menu subcategory title', max_length=64, required=True)), ('items', wagtail.blocks.StreamBlock([('document', wagtail.blocks.StructBlock([('document', wagtail.documents.blocks.DocumentChooserBlock(label='Document', required=True)), ('link_text', wagtail.blocks.CharBlock(label="Link's text", max_length=64, required=False))])), ('external', wagtail.blocks.StructBlock([('link_text', wagtail.blocks.CharBlock(label="Link's text", max_length=64, required=False)), ('url', wagtail.blocks.URLBlock(label='URL', required=True))])), ('page', wagtail.blocks.StructBlock([('link_text', wagtail.blocks.CharBlock(label="Link's text", max_length=64, required=False)), ('page', wagtail.blocks.PageChooserBlock(label='Page', required=True)), ('query_string', wagtail.blocks.CharBlock(label='Query string', max_length=255, required=False))]))]))]))]))])), ('document', wagtail.blocks.StructBlock([('document', wagtail.documents.blocks.DocumentChooserBlock(label='Document', required=True)), ('link_text', wagtail.blocks.CharBlock(label="Link's text", max_length=64, required=False))])), ('external', wagtail.blocks.StructBlock([('link_text', wagtail.blocks.CharBlock(label="Link's text", max_length=64, required=False)), ('url', wagtail.blocks.URLBlock(label='URL', required=True))])), ('page', wagtail.blocks.StructBlock([('link_text', wagtail.blocks.CharBlock(label="Link's text", max_length=64, required=False)), ('page', wagtail.blocks.PageChooserBlock(label='Page', required=True)), ('query_string', wagtail.blocks.CharBlock(label='Query string', max_length=255, required=False))]))], use_json_field=True, verbose_name='Menu items'),
        ),
    ]
