# Generated by Django 3.2.15 on 2022-09-08 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0069_log_entry_jsonfield'),
        ('commontail', '0008_alter_menu_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorhomepagerelation',
            name='page',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.page', verbose_name='page'),
        ),
        migrations.AlterField(
            model_name='authorhomepagerelation',
            name='site',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.site', verbose_name='site'),
        ),
    ]
