# Generated by Django 3.2.15 on 2022-09-13 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commontail', '0010_authorspages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorhomepagerelation',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_pages', to='commontail.author', verbose_name='author'),
        ),
    ]
