# Generated by Django 3.2.4 on 2021-06-14 08:25

import commontail.models.cache
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CacheAwareModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            bases=(commontail.models.cache.AbstractCacheAware, models.Model),
        ),
    ]
